"""Diagnose HSSM safe priors for matching fixed and random slopes.

This marimo notebook reproduces the group-term matching bug reported from
HSSM discussion #948 on a tiny balanced 2x2 dataset. It proves that the
formula is full rank, inspects the priors generated by HSSM, shows the
different failure modes under centered and non-centered parameterizations,
and demonstrates the explicit zero-mean workaround.

No sampling or network access is needed. From the HSSM repository root::

    uv run --group notebook --group docs marimo edit docs/tutorials/random_slope_safe_priors.py
    uv run --group notebook --group docs marimo check --strict docs/tutorials/random_slope_safe_priors.py
    uv run --group notebook --group docs marimo export html \
        docs/tutorials/random_slope_safe_priors.py \
        --output /tmp/random-slope-safe-priors.html --force

The graph cells also require the Graphviz ``dot`` executable (for example,
``brew install graphviz`` on macOS).
"""

# ruff: noqa: B018, D401, E501, PLR1711  (generated marimo notebook: prose, cell display expressions, and bare returns)
import marimo

__generated_with = "0.24.0"
app = marimo.App(width="medium")


@app.cell
def _():
    import logging
    import warnings

    warnings.filterwarnings("ignore")
    logging.getLogger("jax._src.xla_bridge").setLevel(logging.ERROR)
    logging.getLogger("hssm").setLevel(logging.ERROR)

    import bambi as bmb
    import marimo as mo
    import numpy as np
    import pandas as pd
    import pymc as pm
    from formulae import design_matrices

    import hssm
    from hssm.param.parameterization_check import find_disconnected_free_rvs

    hssm.set_floatX("float64")
    return bmb, design_matrices, find_disconnected_free_rvs, hssm, mo, np, pd, pm


@app.cell
def _(bmb, hssm, mo):
    mo.md(f"""
    # Random-slope safe priors and parameterization diagnostics

    This notebook isolates a bug in the default `prior_settings="safe"`
    behavior for a regression containing the same slopes at the population and
    participant levels. It uses **HSSM {hssm.__version__}** and
    **Bambi {bmb.__version__}** from the active environment.

    We will establish four things without running MCMC:

    1. the balanced 2x2 regression is full rank;
    2. affected HSSM versions fail to match group terms such as `x|id` to the
       corresponding common term `x`;
    3. the resulting group-level means are disconnected when non-centered and
       redundant with the fixed slopes when centered; and
    4. explicitly setting every participant-level mean to zero produces the
       intended hierarchical model.

    The notebook is version-adaptive: after HSSM is fixed, it will report that
    the safe defaults already agree with the workaround instead of failing.
    """)
    return


@app.cell
def _(pd):
    rows = []
    for participant in range(2):
        for cell, (block, task) in enumerate([(-1, -1), (-1, 1), (1, -1), (1, 1)]):
            rows.append(
                {
                    "rt": 0.45 + 0.03 * cell + 0.01 * participant,
                    "response": (-1, 1, 1, -1)[cell],
                    "blocktype2_num": block,
                    "task_num": task,
                    "participant_id": f"p{participant}",
                }
            )

    data = pd.DataFrame(rows)
    formula = (
        "v ~ 1 + blocktype2_num*task_num + (1 + blocktype2_num*task_num|participant_id)"
    )
    return data, formula


@app.cell
def _(data, mo):
    mo.md("""
    ## 1. Tiny balanced 2x2 dataset

    There are two participants and exactly one observation in each of the four
    `block x task` cells. Both predictors use the forum post's numeric -1/+1
    coding.
    """)
    data
    return


@app.cell
def _(data, design_matrices, formula, np, pd):
    rhs = formula.split("~", maxsplit=1)[1]
    matrices = design_matrices(f"response ~ {rhs}", data=data)
    common_matrix = np.asarray(matrices.common.design_matrix)
    group_matrix = matrices.group.design_matrix.toarray()

    design_rank_table = pd.DataFrame(
        [
            {
                "design": "common (population)",
                "rows": common_matrix.shape[0],
                "columns": common_matrix.shape[1],
                "rank": np.linalg.matrix_rank(common_matrix),
            },
            {
                "design": "group-specific (both participants)",
                "rows": group_matrix.shape[0],
                "columns": group_matrix.shape[1],
                "rank": np.linalg.matrix_rank(group_matrix),
            },
        ]
    )

    assert np.linalg.matrix_rank(common_matrix) == 4
    assert np.linalg.matrix_rank(group_matrix) == 8
    return design_rank_table, matrices


@app.cell
def _(design_rank_table, mo):
    mo.md("""
    ## 2. The formula is not design-rank overparameterized

    With -1/+1 coding, the common-effect columns are `1`, `block`, `task`, and
    `block:task`. They form a four-column Hadamard matrix within each complete
    participant. The participant-specific design has four independent columns
    for each participant.
    """)
    design_rank_table
    return


@app.cell
def _(matrices, pd):
    matcher_rows = []
    for group_name, term in matrices.group.terms.items():
        matcher_rows.append(
            {
                "group term": group_name,
                "group expression": term.expr.name,
                "full group name in common terms": group_name in matrices.common.terms,
                "expression in common terms": term.expr.name in matrices.common.terms,
            }
        )

    matcher_table = pd.DataFrame(matcher_rows)
    return (matcher_table,)


@app.cell
def _(matcher_table, mo):
    mo.md("""
    ## 3. The exact matching error

    HSSM currently compares the complete group name with the common-term keys.
    A name such as `blocktype2_num|participant_id` cannot equal
    `blocktype2_num`. Formulae already exposes the correct structural name as
    `term.expr.name`.

    The two Boolean columns below reproduce the current and intended matching
    rules. The full names never match; every underlying expression does.
    """)
    matcher_table
    return


@app.cell
def _(data, formula, hssm):
    def zero_mean_participant_prior():
        return {
            "name": "Normal",
            "mu": 0.0,
            "sigma": {
                "name": "Weibull",
                "alpha": 1.5,
                "beta": 0.3,
            },
        }

    group_terms = [
        "1|participant_id",
        "blocktype2_num|participant_id",
        "task_num|participant_id",
        "blocktype2_num:task_num|participant_id",
    ]
    workaround_priors = {term: zero_mean_participant_prior() for term in group_terms}

    def build_model(prior=None, noncentered=True):
        return hssm.HSSM(
            data=data,
            model="ddm",
            include=[
                {
                    "name": "v",
                    "formula": formula,
                    "prior": prior,
                    "link": "identity",
                }
            ],
            prior_settings="safe",
            z=0.5,
            p_outlier=0.0,
            noncentered=noncentered,
            process_initvals=False,
        )

    return build_model, workaround_priors


@app.cell
def _(build_model, workaround_priors):
    safe_noncentered_model = build_model(noncentered=True)
    safe_centered_model = build_model(noncentered=False)
    workaround_model = build_model(
        prior=workaround_priors,
        noncentered=True,
    )
    return safe_centered_model, safe_noncentered_model, workaround_model


@app.cell
def _(bmb, pd, safe_noncentered_model, workaround_model):
    def group_prior_table(model):
        rows = []
        for term_name, prior in model.params["v"].prior.items():
            if "|" not in term_name:
                continue
            mu = prior.args["mu"]
            rows.append(
                {
                    "term": term_name,
                    "mu": repr(mu),
                    "mu is estimated": isinstance(mu, bmb.Prior),
                    "sigma": repr(prior.args["sigma"]),
                }
            )
        return pd.DataFrame(rows)

    safe_prior_table = group_prior_table(safe_noncentered_model)
    workaround_prior_table = group_prior_table(workaround_model)
    return safe_prior_table, workaround_prior_table


@app.cell
def _(mo):
    prior_view = mo.ui.dropdown(
        options={
            "HSSM safe defaults": "safe",
            "Explicit zero-mean workaround": "workaround",
        },
        value="HSSM safe defaults",
        label="Prior specification",
    )
    mo.md(f"""
    ## 4. Compare generated and explicit priors

    {prior_view}

    On an affected HSSM version, the safe default gives each non-intercept
    random slope an estimated `Normal(0, 0.25)` mean. The workaround fixes all
    participant-level means at scalar zero.
    """)
    return (prior_view,)


@app.cell
def _(prior_view, safe_prior_table, workaround_prior_table):
    selected_prior_table = (
        safe_prior_table if prior_view.value == "safe" else workaround_prior_table
    )
    selected_prior_table
    return


@app.cell
def _(
    find_disconnected_free_rvs,
    pd,
    safe_centered_model,
    safe_noncentered_model,
    workaround_model,
):
    safe_disconnected = find_disconnected_free_rvs(safe_noncentered_model.pymc_model)
    centered_disconnected = find_disconnected_free_rvs(safe_centered_model.pymc_model)
    workaround_disconnected = find_disconnected_free_rvs(workaround_model.pymc_model)

    graph_table = pd.DataFrame(
        [
            {
                "prior specification": "HSSM safe defaults",
                "parameterization": "non-centered",
                "disconnected free RVs": ", ".join(safe_disconnected) or "none",
                "count": len(safe_disconnected),
            },
            {
                "prior specification": "HSSM safe defaults",
                "parameterization": "centered",
                "disconnected free RVs": ", ".join(centered_disconnected) or "none",
                "count": len(centered_disconnected),
            },
            {
                "prior specification": "explicit zero means",
                "parameterization": "non-centered",
                "disconnected free RVs": ", ".join(workaround_disconnected) or "none",
                "count": len(workaround_disconnected),
            },
        ]
    )

    assert workaround_disconnected == []
    return graph_table, safe_disconnected


@app.cell
def _(graph_table, mo):
    mo.md("""
    ## 5. What happens to the generated means

    Bambi's non-centered group term is `offset * sigma`; it does not add `mu`.
    On affected HSSM versions, the three generated slope means therefore remain
    free random variables without a path to the likelihood. Fixing `mu=0`
    prevents those variables from being created.

    The centered model has no disconnected means because Bambi uses them in the
    group distributions. That does **not** make the centered model identified.
    """)
    graph_table
    return


@app.cell
def _(mo, safe_disconnected):
    if safe_disconnected:
        matcher_status = mo.callout(
            "This HSSM build still generates disconnected random-slope means "
            "under the safe defaults. The explicit zero-mean workaround removes "
            "them.",
            kind="warn",
        )
    else:
        matcher_status = mo.callout(
            "This HSSM build contains the matcher fix: the safe defaults are "
            "already zero-centered and agree with the workaround.",
            kind="success",
        )
    matcher_status
    return


@app.cell
def _(mo):
    graph_view = mo.ui.dropdown(
        options={
            "Safe defaults, non-centered": "safe_noncentered",
            "Safe defaults, centered": "safe_centered",
            "Explicit zero means, non-centered": "workaround",
        },
        value="Safe defaults, non-centered",
        label="Model graph",
    )
    mo.md(f"""
    ## 6. Inspect the actual PyMC model graphs

    {graph_view}

    These are the graphs PyMC builds, not hand-drawn summaries. Follow the
    arrows to the observed `rt,response` node:

    - **red** nodes are free random variables with no path to the likelihood;
    - **amber** nodes are estimated participant-level population means; and
    - **blue** nodes are the matching common slopes.

    On an affected HSSM build, the non-centered graph has three isolated red
    `*_mu` nodes. Switching those same generated priors to centered connects the
    nodes, but each amber group mean then competes with a blue common slope for
    the same population location. In the workaround graph, the `*_mu` nodes are
    absent because those means are fixed at zero. After the matcher is fixed,
    both safe-default graphs should lose the unintended `*_mu` nodes too.
    """)
    return (graph_view,)


@app.cell
def _(
    graph_view,
    pm,
    safe_centered_model,
    safe_disconnected,
    safe_noncentered_model,
    workaround_model,
):
    _models = {
        "safe_noncentered": safe_noncentered_model,
        "safe_centered": safe_centered_model,
        "workaround": workaround_model,
    }
    _selected_model = _models[graph_view.value]
    _disconnected_names = (
        set(safe_disconnected) if graph_view.value == "safe_noncentered" else set()
    )
    _common_slope_names = {
        "v_blocktype2_num",
        "v_task_num",
        "v_blocktype2_num:task_num",
    }
    _group_mean_names = {
        _name
        for _name in _selected_model.pymc_model.named_vars
        if "|participant_id_mu" in _name
    }

    def _free_rv_formatter(variable):
        _operator_name = getattr(variable.owner.op, "name", None)
        _distribution_name = (
            _operator_name[0].upper() + _operator_name[1:]
            if _operator_name
            else variable.owner.op.__class__.__name__.removesuffix("RV")
        )
        _attributes = {
            "shape": "ellipse",
            "label": f"{variable.name}\n~\n{_distribution_name}",
        }

        if variable.name in _disconnected_names:
            _attributes.update(
                color="#b42318",
                fillcolor="#fee4e2",
                fontcolor="#912018",
                penwidth="3",
                style="filled",
            )
        elif variable.name in _group_mean_names:
            _attributes.update(
                color="#b54708",
                fillcolor="#fef0c7",
                fontcolor="#93370d",
                penwidth="2",
                style="filled",
            )
        elif variable.name in _common_slope_names:
            _attributes.update(
                color="#175cd3",
                fillcolor="#d1e9ff",
                fontcolor="#1849a9",
                penwidth="2",
                style="filled",
            )

        return _attributes

    selected_model_graph = pm.model_to_graphviz(
        _selected_model.pymc_model,
        node_formatters={"Free Random Variable": _free_rv_formatter},
        graph_attr={"bgcolor": "transparent", "rankdir": "LR"},
    )
    selected_model_graph
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 7. Why switching to centered is not the workaround

    For slope (k) and participant (g), a centered group coefficient can be
    written as

    \[
    u_{kg} = \mu_k + \delta_{kg}.
    \]

    When the formula also contains common slope \(\beta_k\), its contribution to
    the linear predictor is

    \[
    \eta_i
      = \beta_k x_{ik} + u_{k,g(i)}x_{ik}
      = (\beta_k + \mu_k)x_{ik} + \delta_{k,g(i)}x_{ik}.
    \]

    The data identify only the combined population location
    \(\beta_k + \mu_k\). Moving a constant from one to the other, while shifting
    the participant coefficients consistently, leaves the likelihood and the
    conditional group distribution unchanged. Their proper top-level priors may
    make the posterior proper, but the two locations are not separately informed
    by the data.

    Therefore `noncentered=False` trades the disconnected-variable symptom for a
    location ridge. The intended model keeps the common slope and fixes the group
    deviation mean at zero.
    """)
    return


@app.cell
def _(mo):
    mo.md("""
    ## 8. Current workaround

    Keep `noncentered=True` and explicitly provide a scalar `mu=0.0` for every
    participant-level coefficient:

    ```python
    def zero_mean_participant_prior():
        return {
            "name": "Normal",
            "mu": 0.0,
            "sigma": {
                "name": "Weibull",
                "alpha": 1.5,
                "beta": 0.3,
            },
        }

    group_terms = [
        "1|participant_id",
        "blocktype2_num|participant_id",
        "task_num|participant_id",
        "blocktype2_num:task_num|participant_id",
    ]

    priors = {
        term: zero_mean_participant_prior()
        for term in group_terms
    }
    ```

    Supply `priors` as the regression parameter's `prior` dictionary. The random
    intercept is already zero-centered by current safe defaults, but specifying
    all four terms makes the model intent explicit and keeps the workaround
    self-contained.
    """)
    return


@app.cell
def _(mo):
    mo.md("""
    ## Takeaway

    The 2x2 regression is full rank. The problematic overparameterization is
    introduced by affected HSSM versions when safe-prior generation gives a
    matching random slope its own population mean. Explicit zero-mean group
    priors are a safe workaround until HSSM matches group expressions to their
    common counterparts structurally.

    Relevant implementation discussions:

    - [HSSM discussion #948](https://github.com/lnccbrown/HSSM/discussions/948)
    - [HSSM issue #1224](https://github.com/lnccbrown/HSSM/issues/1224)
    - [Bambi issue #1003](https://github.com/bambinos/bambi/issues/1003)
    - [Formulae term structure](https://github.com/bambinos/formulae/blob/main/formulae/terms/terms.py)
    """)
    return


if __name__ == "__main__":
    app.run()
