name: Setup Python environment
description: Set up Python environment for the repository
inputs:
  python-version:
    description: "The Python version to set up"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        version: "latest"
        enable-cache: true

    - name: Install hssm
      run: uv sync --group notebook
      shell: bash
