name: Check notebooks

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check_notebooks:
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.head_commit.message, '[skip fast tests]') }}
    env:
      PYTENSOR_FLAGS: "blas__ldflags=-L/usr/lib/x86_64-linux-gnu -lblas -llapack"

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true

      - name: Setup environment
        run: uv sync --group notebook

      - name: Run notebooks
        run: make run-notebooks
        env:
          PYTENSOR_FLAGS: ${{ env.PYTENSOR_FLAGS }}
