name: Run fast tests

on:
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.head_commit.message, '[skip fast tests]') }}
    env:
      PYTENSOR_FLAGS: "blas__ldflags=-L/usr/lib/x86_64-linux-gnu -lblas -llapack"

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Poetry environment
        uses: ./.github/setup-poetry-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run fast tests
        run: poetry run pytest -n auto -s --ignore=tests/slow
        env:
          PYTENSOR_FLAGS: ${{ env.PYTENSOR_FLAGS }}

      - name: Run jupyter notebooks in docs
        run: poetry run mkdocs build
        env:
          PYTENSOR_FLAGS: ${{ env.PYTENSOR_FLAGS }}
